export const refs = {
  men: document.querySelectorAll(".man__image"),
  server: document.querySelector(".server__image.europe"),
  link: document.querySelector(".next-link"),
  linkModal: document.querySelector(".modal__link"),
  title: document.querySelector(".title"),
  devices: document.querySelectorAll(".device__image"),
  devicesDisplay: document.querySelectorAll(".device-display__image"),
  circlesEmpty: document.querySelectorAll(".circle__image--empty"),
  circles: document.querySelectorAll(".circle__image--filled"),
  backdrop: document.querySelector(".backdrop"),
  servers: document.querySelectorAll(".server__image"),
  infos: document.querySelectorAll(".latency-time"),
  infosValue: document.querySelectorAll(".latency-time__value"),
  arrows: document.querySelectorAll(".arrow"),
  modalLeft: document.querySelector(".modal__table--left"),
  modalRight: document.querySelector(".modal__table--right"),
};